import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "sonner";
import Footer from "@/components/footer";
import { ClerkProvider } from '@clerk/nextjs'
import { Inter} from "next/font/google";
const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider  >
    <html lang="en" suppressHydrationWarning>
      <body
       className={`${inter.className}`}
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
           {/* Header */}
              <Header/>
              <main className="min-h-screen">{children}</main>
              <Toaster richColors/>
            
            <Footer/>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
